name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Impostazione di JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Dare i permessi a gradlew
      run: chmod +x ./gradlew

    # === NUOVO PASSO DI PULIZIA ===
    - name: Pulisci la Build (Clean Build)
      run: ./gradlew clean --stacktrace

    - name: Compilare con Gradle
      run: ./gradlew build --stacktrace

    - name: Caricare l'artefatto APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        if-no-files-found: error
        path: app/build/outputs/apk/debug/app-debug.apk
