# ===================================================================
# File: .github/workflows/android-build.yml
# Revisione Finale (Build Stabile e Riproducibile)
# - Blocca la versione di Gradle a 8.6 per evitare instabilità.
# - Mantiene l'approccio robusto che usa 'gradle' invece di './gradlew'.
# ===================================================================
name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Impostazione di JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        # Blocchiamo la versione per garantire una build stabile e riproducibile
        gradle-version: 8.6

    - name: Compilare con Gradle
      run: gradle build --stacktrace

    - name: Caricare l'artefatto APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        if-no-files-found: error
        path: app/build/outputs/apk/debug/app-debug.apk
