# ===================================================================
# File: .github/workflows/android-build.yml
# Versione Finale Stabile per ChronoLog
# ===================================================================
name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Scarica il codice del repository
    - name: Checkout del codice
      uses: actions/checkout@v4

    # 2. Imposta l'ambiente Java (JDK 17)
    - name: Impostazione di JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    # 3. Dare i permessi di esecuzione al Gradle Wrapper
    # Questo passo è necessario perché i permessi potrebbero non essere
    # preservati durante l'upload da Windows/ZIP.
    - name: Dare i permessi a gradlew
      run: chmod +x ./gradlew

    # 4. Esegue la compilazione
    # Il comando 'build' è più completo di 'assembleDebug' e include
    # la verifica di lint e altri controlli di qualità.
    - name: Compilare con Gradle
      run: ./gradlew build --stacktrace

    # 5. Salva l'APK generato per il download
    # Cerca l'APK di debug nella cartella di output standard.
    - name: Caricare l'artefatto APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
